// <auto-generated />
using ConstructionSubmittal_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConstructionSubmittal_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512080342_AddCompanyTableAndSeedData")]
    partial class AddCompanyTableAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConstructionSubmittal_API.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Big Street",
                            CompanyType = 2,
                            Name = "Big General Contractors"
                        },
                        new
                        {
                            Id = 2,
                            Address = "5555 West Boulevard",
                            CompanyType = 3,
                            Name = "Diamond Architecture"
                        },
                        new
                        {
                            Id = 3,
                            Address = "101 Electric Road",
                            CompanyType = 1,
                            Name = "Spark Electrical"
                        });
                });

            modelBuilder.Entity("ConstructionSubmittal_API.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Lockport Road",
                            JobNumber = "001",
                            Name = "Lockport High School"
                        },
                        new
                        {
                            Id = 2,
                            Address = "520 Main Street",
                            JobNumber = "002",
                            Name = "Lockport Animal Hospital"
                        },
                        new
                        {
                            Id = 3,
                            Address = "101 Center Drive",
                            JobNumber = "003",
                            Name = "Wendys"
                        });
                });

            modelBuilder.Entity("ConstructionSubmittal_API.Models.Submittal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SpecSection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Submittals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectId = 1,
                            Status = 0,
                            Title = "Interior Lighting : Product Data",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            ProjectId = 1,
                            Status = 0,
                            Title = "Exterior Lighting : Product Data",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            ProjectId = 1,
                            Status = 0,
                            Title = "Interior Lighting : Shop Drawing",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            ProjectId = 2,
                            Status = 0,
                            Title = "Steel Framing : Shop Drawing",
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            ProjectId = 2,
                            Status = 0,
                            Title = "Steel Framing : Product Data",
                            Type = 0
                        });
                });

            modelBuilder.Entity("ConstructionSubmittal_API.Models.Project", b =>
                {
                    b.HasOne("ConstructionSubmittal_API.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ConstructionSubmittal_API.Models.Submittal", b =>
                {
                    b.HasOne("ConstructionSubmittal_API.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
