// <auto-generated />
using ConstructionSubmittal_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConstructionSubmittal_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501045516_ChangeProjectPropertiesToRequired")]
    partial class ChangeProjectPropertiesToRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConstructionSubmittal_API.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Lockport Road",
                            JobNumber = "001",
                            Name = "Lockport High School"
                        },
                        new
                        {
                            Id = 2,
                            Address = "520 Main Street",
                            JobNumber = "002",
                            Name = "Lockport Animal Hospital"
                        },
                        new
                        {
                            Id = 3,
                            Address = "101 Center Drive",
                            JobNumber = "003",
                            Name = "Wendys"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
